/* This file is automatically generated. Do not edit. */
#ifndef VERSION_H
#define VERSION_H

#define VERSION "0.7.4"
#define GIT_BRANCH "master"
#define GIT_HASH "android-port"
#define GIT_DATE "2026-07-25"

#endif
